name: Docs Deployment

on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install livereload
          pip install -r docs/requirements-docs.txt

      - name: Build and Deploy Documentation
        run: mkdocs gh-deploy --force
