AI_applications:
  sales_model:
    vectordb:
      index_name: "sales_index"
      data_path: "securechat/sales/data"
      vector_type: "opensearch"

opensearch:
  user: "admin"
  password: "Paig2024@"
  hosts: "opensearch-node1:9200"