name: Build Python Package
on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Ensure the repo is checked out

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install virtualenv
        virtualenv -p python3 venv && . venv/bin/activate
        pip install twine build pytest pytest-cov
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        . venv/bin/activate && cd user_manager
        python3 -m pytest tests
        filepath_pytest=$PWD
        echo $filepath_pytest


    - name: Build the wheel
      run: |
        filepath=$PWD
        echo "Build wheel filepath"
        echo $filepath
        . venv/bin/activate
        python3 -m build -w

    - name: Install created package
      run: |
          rm -rf venv
          virtualenv -p python3 venv && . venv/bin/activate
          pip install dist/*.whl