name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install virtualenv
          virtualenv -p python3 venv && . venv/bin/activate
          pip install -r requirements.txt
          pip install requests

      - name: Generate Changelog Entry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . venv/bin/activate
          python generate_changelog.py

      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: 'Siddheshwar Kamble'
          GIT_AUTHOR_EMAIL: 'siddhukamble45@gmail.com'
          GIT_COMMITTER_NAME: 'Siddheshwar Kamble'
          GIT_COMMITTER_EMAIL: 'siddhukamble45@gmail.com'
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release"
          git push https://x-access-token:${GIT_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
